name: jarlenmodas
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  window_manager : ^0.5.1
  mask_text_input_formatter: ^2.1.0
  cloud_firestore : ^6.0.0
  firebase_storage: ^13.0.0

  cupertino_icons: ^1.0.6
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  go_router: ^16.1.0
  pluto_grid: ^8.0.0
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
     - assets/images/logo_empresa.png
     - assets/images/backgroud-image.png
     - assets/images/logo_empresa_nav.png

  uses-material-design: true
