name: jarlenmodas
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  window_manager : ^0.5.1
  mask_text_input_formatter: ^2.1.0
  cloud_firestore : ^6.0.0
  firebase_storage: ^13.0.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  go_router: ^16.1.0
  pluto_grid: ^8.0.0
  flutter_bloc: ^8.1.3
  reactive_forms: ^17.0.0
  toastification: 3.0.3
  uuid: ^4.4.0
  image_picker: ^1.1.2
  image: ^4.1.7
  intl: ^0.19.0
  currency_text_input_formatter: ^2.0.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  image_path: "assets/images/windows_apllication_icon.ico"
  windows:
    generate: true
  web:
    generate: false
flutter:
  assets:
     - assets/images/logo_empresa.png
     - assets/images/backgroud-image.png
     - assets/images/logo_empresa_nav.png

  uses-material-design: true