// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB480a396XxGLukS4qHnHGA3PUC811rQi4',
    appId: '1:949412297273:web:d6f3eecc8bd6b652afebe8',
    messagingSenderId: '949412297273',
    projectId: 'jarlen-modas-fernando',
    authDomain: 'jarlen-modas-fernando.firebaseapp.com',
    storageBucket: 'jarlen-modas-fernando.firebasestorage.app',
    measurementId: 'G-BB9TXYWQ42',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB480a396XxGLukS4qHnHGA3PUC811rQi4',
    appId: '1:949412297273:web:39d96dc1305a842dafebe8',
    messagingSenderId: '949412297273',
    projectId: 'jarlen-modas-fernando',
    authDomain: 'jarlen-modas-fernando.firebaseapp.com',
    storageBucket: 'jarlen-modas-fernando.firebasestorage.app',
    measurementId: 'G-2RGP5WC0VV',
  );
}
