// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUWX9GW_JheXwagPaUvwUk4yUxcImd35U',
    appId: '1:666930471446:web:de517b5dfe22400aaf0b37',
    messagingSenderId: '666930471446',
    projectId: 'jarlen-modas',
    authDomain: 'jarlen-modas.firebaseapp.com',
    storageBucket: 'jarlen-modas.firebasestorage.app',
    measurementId: 'G-KJTJKLMR9L',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUWX9GW_JheXwagPaUvwUk4yUxcImd35U',
    appId: '1:666930471446:web:d738e33b18ad6c2eaf0b37',
    messagingSenderId: '666930471446',
    projectId: 'jarlen-modas',
    authDomain: 'jarlen-modas.firebaseapp.com',
    storageBucket: 'jarlen-modas.firebasestorage.app',
    measurementId: 'G-2W7PC49DES',
  );
}
